### ISSUE TITLE
UX: no path to review matched components

### ISSUE THREAD

**Issue by lucasgonze** [scanoss/sbom-workbench#445]
1. Go to Reports > Detected
2. In "Licenses", select a license of interest, such as GPL
<img width="421" alt="image" src="https://user-images.githubusercontent.com/111581/173684561-9c49833b-d4e5-47c6-90ec-a26f29571470.png">
3. Examine the "Matches for license" list
<img width="420" alt="image" src="https://user-images.githubusercontent.com/111581/173684654-20d733b7-26a6-4326-9e48-21d7ac77a31a.png">
4. Identify an item of interest, such as mysql-connector-java, and click to investigate further

- Expect: view matches
- Actual: nothing happens

**Comment by brunodeangelis** [comment]
Hi @lucasgonze! I'm Bruno, Product Designer at SCANOSS. Thank you very much for creating this issue, and sorry this response is coming late. I love seeing these because it helps us a lot to improve the application. 

I'd like to know what exactly you mean by "view matches". Could you expand on that? What information is valuable for you to see once you click on a component?

Cheers!

**Comment by lucasgonze** [comment]
Hi Bruno, glad to connect. My hope with the issues I've been submitting is to pay it forward :-) Feel free to ask for any usability information I can offer.

The information I would find valuable is where the component is referenced. In a complex code base, it can be slow work to figure out the location.

**Comment by brunodeangelis** [comment]
> Hi Bruno, glad to connect. My hope with the issues I've been submitting is to pay it forward :-) Feel free to ask for any usability information I can offer.
> 
> The information I would find valuable is where the component is referenced. In a complex code base, it can be slow work to figure out the location.

Lucas, we will include this fix in the next release. Once it's out, we'll close the issue.

Thank you very much for your comments!

**Comment by francostramana** [comment]
Hi @lucasgonze,  I'm glad to let you know that we have made improvements to the reporting UX in which we included your proposal. The work is already integrated, in a few hours the official version (1.10.0) will be published.

Regards!

**Comment by lucasgonze** [comment]
Looking forward to checking out the new version.
