### ISSUE TITLE
NODE 18 doesn't correctly work with MUI package.

### ISSUE THREAD

**Issue by surister** [scanoss/sbom-workbench#589]
If you attempt to install with **v19.9.0** in my case, you get a:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @mui/styles@5.13.2
npm ERR! Found: react@18.2.0
```

It's known and reported https://github.com/mui/material-ui/issues/32982

It can be ''fixed'' with `npm install --force`

Maybe change the prerequisites **Node.js v14** to something else or note this somewhere?

**Comment by francostramana** [comment]
Hey @surister apparently it is not a problem with the Node version. Unfortunately @mui/styles@5.13.2 [isn't compatible with react 18](https://mui.com/system/styles/basics/). We could drop the dependency and use an alternative styling solution but that would take a lot of effort. 

We decide keep the dependency and update the readme file adding the `--legacy-peer-deps` params and address to the issue until there is an official solution of the MUI library.
