### ISSUE TITLE
Error: Scanning Reason: Cannot recovery index on winnower

### ISSUE THREAD

**Issue by SkyzcYou** [scanoss/sbom-workbench#625]
ENV: Linux operating system - workbench-1.8.2

Error: Scanning 
Reason: Cannot recovery index on winnower

What does mean when this error occurs?

![2023-11-16-16-46-55-669](https://github.com/scanoss/sbom-workbench/assets/34330885/41f57093-6381-4353-b7df-adfff5f297fe)

**Comment by francostramana** [comment]
Hi @SkyzcYou, kindly update to the latest version to resolve this issue. The bug has been fixed.

https://scanoss.com/download
